name: Schematics

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - "**.kicad_pcb"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: kicad-exports schematic docs
        uses: nerdyscout/kicad-exports@master
        with:
          config: /opt/kibot/config/docs.kibot.yaml
          board: STM32F_rev3/STM32F_rev3.kicad_pcb
          schema: STM32F_rev3/STM32F_rev3.sch
      - name: kicad-exports plots
        uses: nerdyscout/kicad-exports@master
        with:
          config: plot.kiplot.yaml
          board: STM32F_rev3/STM32F_rev3.kicad_pcb
          schema: STM32F_rev3/STM32F_rev3.sch
      - name: kicad-schematic
        uses: andstor/file-existence-action@v1
        with:
          files: "STM32F_rev3/docs/test_schematic.svg, STM32F_rev3/docs/test_schematic.pdf"
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: schematic
          path: docs
